import { expect, test } from "@playwright/test";
import { openDashboard } from "./helpers";

test("member edits prefill current values, discard cancellation, persist saves and support unassignment", async ({ page }) => {
  await openDashboard(page, "/members");
  const members = page.getByRole("region", { name: "구성원 목록", exact: true });
  const firstEdit = members.getByRole("button", { name: /팀\/역할 수정$/ }).first();
  const account = (await firstEdit.getAttribute("aria-label"))!.replace(" 팀/역할 수정", "");
  await firstEdit.click();
  const modal = page.getByRole("dialog", { name: "팀/역할 수정", exact: true });
  const team = modal.getByLabel("팀", { exact: true });
  const role = modal.getByLabel("역할", { exact: true });
  const save = modal.getByRole("button", { name: "변경 저장", exact: true });
  const initialTeam = await team.inputValue();
  const initialRole = await role.inputValue();
  const newTeam = initialTeam === "team-2" ? "team-1" : "team-2";
  const newRole = initialRole === "lead" ? "admin" : "lead";
  await expect(modal).toContainText(account);
  await expect(save).toBeDisabled();
  await team.selectOption(newTeam);
  await role.selectOption(newRole);
  await modal.getByRole("button", { name: "취소", exact: true }).click();
  await expect(modal).not.toBeVisible();
  await firstEdit.click();
  await expect(team).toHaveValue(initialTeam);
  await expect(role).toHaveValue(initialRole);
  await team.selectOption(newTeam);
  await role.selectOption(newRole);
  await save.click();
  await expect(modal).not.toBeVisible();
  await expect(page.getByRole("status").filter({ hasText: `${account}의 팀·역할을 변경했습니다.` })).toBeVisible();
  await page.getByRole("link", { name: "개요", exact: true }).click();
  await page.getByRole("link", { name: "구성원", exact: true }).click();
  const edit = members.getByRole("button", { name: `${account} 팀/역할 수정`, exact: true });
  await edit.click();
  await expect(team).toHaveValue(newTeam);
  await expect(role).toHaveValue(newRole);
  await team.selectOption("");
  await role.selectOption("viewer");
  await save.click();
  await expect(modal).not.toBeVisible();
  const row = edit.locator("..");
  await expect(row.getByText("미배정", { exact: true })).toBeVisible();
  await expect(row.getByText("조회 전용", { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await edit.click();
  await expect(team).toHaveValue("");
  await expect(role).toHaveValue("viewer");
  await expect(modal.locator("section").locator("..")).toHaveCSS("opacity", "1");
  const bounds = (await modal.locator("section").boundingBox())!;
  expect(bounds.x).toBeGreaterThanOrEqual(0);
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(390);
  await page.screenshot({ path: "test-results/member-edit-mobile.png" });
  await page.keyboard.press("Escape");
  await expect(modal).not.toBeVisible();
  await expect(edit).toBeFocused();
});

test("pending invitations can be edited from either list without changing their expiry", async ({ page }) => {
  await openDashboard(page, "/members");
  await page.getByRole("button", { name: "구성원 초대", exact: true }).click();
  const invitation = page.getByRole("dialog", { name: "구성원 초대", exact: true });
  const email = invitation.getByRole("textbox", { name: "초대할 이메일" });
  await email.fill("edit@example.com");
  await email.press("Enter");
  await invitation.getByRole("combobox", { name: "팀", exact: true }).selectOption("team-1");
  await invitation.getByRole("button", { name: "1명에게 초대 메일 발송", exact: true }).click();
  await invitation.getByRole("button", { name: "취소", exact: true }).click();
  await expect(invitation).not.toBeVisible();
  const pending = page.getByRole("region", { name: "초대 대기", exact: true });
  const expiry = await pending.locator("span").filter({ hasText: /^\d+일 남음$/ }).innerText();
  await pending.getByRole("button", { name: "edit@example.com 초대 팀/역할 수정", exact: true }).click();
  const modal = page.getByRole("dialog", { name: "팀/역할 수정", exact: true });
  await expect(modal.getByLabel("팀", { exact: true })).toHaveValue("team-1");
  await expect(modal.getByLabel("역할", { exact: true })).toHaveValue("member");
  await expect(modal).toContainText("초대를 수락하면 변경한 팀과 역할이 적용됩니다.");
  await modal.getByLabel("팀", { exact: true }).selectOption("team-2");
  await modal.getByLabel("역할", { exact: true }).selectOption("lead");
  await modal.getByRole("button", { name: "변경 저장", exact: true }).click();
  await expect(modal).not.toBeVisible();
  await expect(pending).toContainText("데이터 · 팀 리드");
  await expect(pending).toContainText(expiry);
  const members = page.getByRole("region", { name: "구성원 목록", exact: true });
  await members.getByRole("textbox", { name: "구성원 검색" }).fill("edit@example.com");
  await members.getByRole("button", { name: "edit@example.com 팀/역할 수정", exact: true }).click();
  await expect(modal.getByLabel("팀", { exact: true })).toHaveValue("team-2");
  await expect(modal.getByLabel("역할", { exact: true })).toHaveValue("lead");
  await modal.getByLabel("팀", { exact: true }).selectOption("");
  await modal.getByLabel("역할", { exact: true }).selectOption("viewer");
  await expect(modal.locator("section").locator("..")).toHaveCSS("opacity", "1");
  await page.screenshot({ path: "test-results/invite-edit-desktop.png" });
  await modal.getByRole("button", { name: "변경 저장", exact: true }).click();
  await expect(modal).not.toBeVisible();
  await expect(pending).toContainText("팀 미배정 · 조회 전용");
  await expect(pending).toContainText(expiry);
  await expect(members.getByText("신호 대기", { exact: true })).toBeVisible();
});
