import { expect, test } from "@playwright/test";
import { openDashboard } from "./helpers";

test("pending invitations remain below the cards with resend and revoke actions", async ({ page }) => {
  await openDashboard(page, "/members");
  await expect(page.getByRole("region", { name: "등록한 개발자", exact: true })).toHaveCount(0);
  const pending = page.getByRole("region", { name: "초대 대기", exact: true });
  await expect(pending).toContainText("초대 대기 중인 구성원이 없습니다");
  const cards = pending.locator("..");
  expect(await cards.locator(":scope > *").evaluateAll((children) => children.findIndex((child) => child.getAttribute("aria-label") === "초대 대기"))).toBe(4);
  await page.getByRole("button", { name: "구성원 초대", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "구성원 초대", exact: true });
  const email = dialog.getByRole("textbox", { name: "초대할 이메일" });
  await email.fill("pending@example.com");
  await email.press("Enter");
  await dialog.getByRole("button", { name: "1명에게 초대 메일 발송", exact: true }).click();
  await dialog.getByRole("button", { name: "취소", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(pending).toContainText("pending@example.com");
  await page.clock.install();
  await pending.getByRole("button", { name: "다시 보내기" }).click();
  await expect(pending.getByRole("button", { name: "보내는 중…", exact: true })).toBeDisabled();
  await expect(pending.getByRole("button", { name: "취소", exact: true })).toBeDisabled();
  await expect(pending.getByRole("status")).toContainText("초대 메일 재발송을 처리하고 있습니다");
  await page.clock.runFor(600);
  await expect(pending.getByRole("status")).toContainText("재발송 처리가 완료되었습니다");
  await expect(pending.getByRole("status")).toContainText("실제 메일 미발송");
  await expect(pending.getByRole("button", { name: "다시 보내기", exact: true })).toBeEnabled();
  await expect(pending).toContainText("7일 남음");
  const members = page.getByRole("region", { name: "구성원 목록", exact: true });
  await members.getByRole("textbox", { name: "구성원 검색" }).fill("pending@example.com");
  await expect(members.getByText("기록 없음", { exact: true })).toBeVisible();
  await expect(members.getByRole("button", { name: "pending@example.com 구성원 상세", exact: true })).toBeVisible();
  await expect(members.getByText("벤더 좌석", { exact: true })).toHaveCount(0);
  await page.screenshot({ path: "test-results/members-pending-desktop.png", fullPage: true });
  await members.screenshot({ path: "test-results/members-table-desktop.png" });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "내비게이션 접기/펼치기" }).click();
  await members.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/members-pending-mobile.png", fullPage: true });
  await members.locator(".overflow-x-auto").evaluate((element) => { element.scrollLeft = element.scrollWidth; });
  await members.screenshot({ path: "test-results/members-table-mobile.png" });
  await pending.getByRole("button", { name: "취소", exact: true }).click();
  await expect(pending).toContainText("초대 대기 중인 구성원이 없습니다");
  await expect(members.getByText("pending@example.com", { exact: true })).toHaveCount(0);
});
