import { expect, test } from "@playwright/test";
import { openDashboard } from "./helpers";

test("overview separates people and contract tiers, and keeps unknown allocation explicit", async ({ page }) => {
  await openDashboard(page, "/overview");
  await expect(page.locator("span").getByText("사용 관측 인원", { exact: true })).toBeVisible();
  await expect(page.getByText("활성 좌석", { exact: true })).toHaveCount(0);
  await expect(page.getByText("좌석 효율", { exact: true })).toHaveCount(0);
  const table = page.getByRole("table", { name: "계약·좌석 현황" });
  const claude = table.locator('tbody tr[data-vendor-id="claude_team"]');
  await expect(claude).toHaveCount(1);
  await expect(claude).toContainText("148석");
  await expect(table.getByRole("columnheader", { name: "워크스페이스" })).toHaveCount(0);
  await expect(table.getByRole("row").filter({ hasText: "GitHub Copilot" })).toContainText("2석");
  await claude.getByRole("button").click();
  const detail = page.getByRole("dialog", { name: "Claude 현황" });
  await expect(detail).toContainText("표준 · 125석");
  await expect(detail).toContainText("프리미엄 · 23석");
  await page.keyboard.press("Escape");
  await expect(detail).not.toBeVisible();
  await expect(claude.getByRole("button")).toBeFocused();
  const before = await claude.getByRole("cell").nth(3).innerText();
  await page.getByRole("toolbar", { name: "전역 필터" }).getByRole("button", { name: /^\d{4}\.\d{2}\.\d{2} ~ / }).click();
  const calendar = page.getByRole("dialog", { name: "기간 선택" });
  await calendar.getByRole("button", { name: "오늘", exact: true }).click();
  await calendar.getByRole("button", { name: "적용", exact: true }).click();
  await expect(page.getByRole("slider")).toHaveAttribute("aria-valuemax", "1");
  await expect(claude.getByRole("cell").nth(3)).toHaveText(before);
  await expect(claude).toContainText("148석");
  await page.getByRole("main").evaluate((element) => element.scrollTo(0, 0));
  await page.screenshot({ path: "test-results/overview-seats-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "내비게이션 접기/펼치기" }).click();
  await table.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const scroll = table.locator("..");
  await scroll.evaluate((element) => { element.scrollLeft = element.scrollWidth; });
  expect(await scroll.evaluate((element) => element.scrollLeft)).toBeGreaterThan(0);
  await page.screenshot({ path: "test-results/overview-seats-mobile.png", fullPage: true });
});

test("settings contract additions propagate to overview without inventing free seats", async ({ page }) => {
  await openDashboard(page, "/overview");
  await page.getByRole("link", { name: "계약 설정 →", exact: true }).click();
  await page.getByRole("button", { name: "벤더 추가", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("표시 이름", { exact: true }).fill("Overview review vendor");
  await dialog.getByLabel("좌석 수", { exact: true }).fill("10");
  await dialog.getByLabel("월 단가", { exact: true }).fill("5");
  await dialog.getByRole("button", { name: "벤더 추가", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole("navigation", { name: "주 내비게이션" }).getByRole("link", { name: "개요", exact: true }).click();
  const row = page.getByRole("table", { name: "계약·좌석 현황" }).getByRole("row").filter({ hasText: "GitHub Copilot" });
  await expect(row).toContainText("12석");
  await expect(row.getByRole("cell").nth(2)).toHaveText("미관측");
  await expect(row.getByRole("cell").nth(3)).toHaveText("—");
  const monthly = page.locator("span").getByText("월 좌석 계약액", { exact: true }).locator("../..");
  await expect(monthly).toContainText("4,850");
});
