import { expect, test } from "@playwright/test";
import { saveOnboardingContract, signIn } from "./helpers";

test("onboarding and team management reject emoji names while preserving valid assignments", async ({ page }) => {
  await page.goto("/login");
  await signIn(page);
  await page.getByRole("radio", { name: /^수집하지 않음/ }).check();
  await page.getByRole("button", { name: "다음", exact: true }).click();
  await saveOnboardingContract(page);
  await page.getByRole("button", { name: "다음", exact: true }).click();
  const name = page.getByRole("textbox", { name: "팀 이름", exact: true });
  await name.fill("개발팀🚀");
  await page.getByRole("button", { name: "팀 생성", exact: true }).click();
  await expect(name).toHaveValue("개발팀🚀");
  await expect(name).toHaveAttribute("aria-invalid", "true");
  await expect(name).toHaveAccessibleDescription(/이모지와 허용되지 않은 문자/);
  await expect(page.getByRole("list", { name: "온보딩 팀 목록" })).not.toContainText("개발팀🚀");
  await name.fill("R&D");
  await page.getByRole("button", { name: "팀 생성", exact: true }).click();
  await expect(page.getByRole("list", { name: "온보딩 팀 목록" })).toContainText("R&D");
  await page.getByRole("button", { name: "완료", exact: true }).click();
  await page.getByRole("link", { name: "구성원", exact: true }).click();
  await page.getByRole("button", { name: "팀 관리", exact: true }).click();
  const drawer = page.getByRole("dialog", { name: "팀 관리", exact: true });
  await drawer.getByRole("button", { name: "R&D 팀 수정", exact: true }).click();
  const editName = drawer.getByRole("textbox", { name: "팀 이름", exact: true });
  await editName.fill("팀👩‍💻");
  await drawer.getByRole("button", { name: "변경 저장", exact: true }).click();
  await expect(editName).toHaveAttribute("aria-invalid", "true");
  await drawer.getByRole("button", { name: "취소", exact: true }).click();
  await expect(drawer.getByRole("button", { name: "R&D 팀 수정", exact: true })).toBeVisible();
  await drawer.getByRole("button", { name: "팀 만들기", exact: true }).click();
  await editName.fill("---");
  await drawer.getByRole("button", { name: "팀 생성", exact: true }).click();
  await expect(editName).toHaveAccessibleDescription(/하나 이상 포함/);
  await editName.fill("AI/ML");
  await drawer.getByRole("button", { name: "팀 생성", exact: true }).click();
  await expect(drawer.getByRole("button", { name: "AI/ML 팀 수정", exact: true })).toBeVisible();
});
