/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관리자 로그인 (이메일 + 비밀번호 → Bearer 토큰)
         * @description `enrollment.members.email` + `password_hash`(Spring Security PasswordEncoder, ADR 0007) 검증.
         *     role ∈ {owner, admin} 이고 status='active' 인 구성원만 로그인 가능. **가정 A4**: 토큰 형식·만료는 Spring Security 구성에 따름.
         */
        post: operations["AUTH-LOGIN"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 로그인 사용자·테넌트·역할·접근 가능 팀 */
        get: operations["ME"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지표 조회 — 위젯 하나가 한 번 호출, 여러 지표는 queries[]로 묶음
         * @description Grafana `POST /api/ds/query` 차용. 요청 본문의 `queries[]` 각 항목이 `ref_id`를 가지고,
         *     응답 `results`의 키가 그 `ref_id`다. 시간 범위·전역 필터는 본문 최상위(공통) 또는 쿼리별로 덮어쓸 수 있다.
         *
         *     `Accept: text/csv` 이면 첫 번째 쿼리의 프레임을 CSV로 내려준다(내보내기).
         */
        post: operations["QRY"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지표 카탈로그 — metric_id별 정의·허용 group_by·원천 컬럼·가용성
         * @description 프론트가 위젯 정의 툴팁(ⓘ)과 group_by 옵션을 이 응답으로 그린다. 서버 쪽 SQL 템플릿의 진실원.
         */
        get: operations["META-METRICS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 전역 필터 옵션 일괄 조회 (팀·제품·모델·기간 프리셋) */
        get: operations["META-FILTERS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 팀 목록 (enrollment.teams + 현재 인원) */
        get: operations["META-TEAMS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 구성원 목록 (enrollment.members + 설치 수) — P5 설정·P3 필터용 */
        get: operations["META-MEMBERS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 기간 내 관측된 모델 목록 */
        get: operations["META-MODELS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 계약·토큰 할인·약정 (P5 설정, 계약 단가 환산 근거) */
        get: operations["META-CONTRACTS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/manifests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 수집 정책(manifest) 배포 상태 (P5 설정, P3 컴플라이언스) */
        get: operations["META-MANIFESTS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 설치 목록 — 커버리지·무활동 시트 (P3 컴플라이언스 표, S1-7) */
        get: operations["INSTALL-LIST"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 세션 상관 조회 (감사 로그 필수) — P3 세션 조회
         * @description `raw_json.envelope.session_id` 로 세션 전체 이벤트를 시간순으로 돌려준다. **개인 활동 재구성에 해당**하므로
         *     role ∈ {owner, admin} + `X-Audit-Reason` 필수, 조회자·사유·session_id를 감사 로그에 기록한다.
         *     `request_id`, `tool_use_id`(call_id), `installation_id` 로도 검색하려면 `lookup` 파라미터를 쓴다.
         */
        get: operations["SESSION-EVENTS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 시나리오 카탈로그 (46개, 가용성 포함)
         * @description 시나리오 문서의 8 카테고리 46개 전부를 싣는다. `availability=unavailable`(어댑터가 드롭하는 이벤트·원문·외부 데이터 의존)이면
         *     UI가 카드를 "준비 중"으로 비활성화하고, 실행 요청은 409를 받는다. 검증 기준 "모든 시나리오가 UI·API에 반영"을 이 응답이 만족한다.
         */
        get: operations["SCN-LIST"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 시나리오 상세 — 파라미터 스키마·지표·판정 규칙 */
        get: operations["SCN-GET"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 시나리오 실행 (비동기) — 202 + run_id
         * @description 실행은 **비동기**다. 서버는 `params_schema` 검증 후 큐에 넣고 202를 돌려준다. 클라이언트는 `GET /scenario-runs/{run_id}`를
         *     `Retry-After`(초) 간격으로 폴링한다. 한 실행은 `metric_ids`에 해당하는 `POST /query`와 같은 SQL 템플릿을 순차 실행하고
         *     `findings_rules`를 적용한다. 결과는 `dashboard.scenario_runs`에 저장되어 공유 링크(`/runs/{run_id}`)로 재열람된다.
         *     (동기 실행이 필요하면 `?wait=true`로 최대 20초까지 기다린 뒤 완료 시 200, 미완료 시 202.)
         */
        post: operations["SCN-RUN"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실행 이력 (테넌트 전체, 최신순) */
        get: operations["RUN-LIST"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 실행 상태·결과 조회 (폴링 대상) */
        get: operations["RUN-GET"];
        put?: never;
        post?: never;
        /** 실행 이력 삭제 (실행자 또는 owner) */
        delete: operations["RUN-DELETE"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario-runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 실행 취소 (queued/running 일 때) */
        post: operations["RUN-CANCEL"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario-runs/{run_id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 결과를 저장 리포트로 보관 (이름·메모·기간 고정 여부) */
        post: operations["RUN-SAVE"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 저장 리포트 목록 */
        get: operations["SAVED-LIST"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-reports/{saved_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 저장 리포트 삭제 */
        delete: operations["SAVED-DELETE"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description enrollment 서버 에러 계약 `{error, message}` 에 `request_id` 를 더한 형태. 예외 메시지 원문은 싣지 않는다. */
        Error: {
            /** @enum {string} */
            error: "invalid_request" | "unauthorized" | "forbidden" | "audit_reason_required" | "not_found" | "group_by_not_allowed" | "query_too_wide" | "query_timeout" | "scenario_unavailable" | "run_limit_exceeded" | "conflict" | "internal_error";
            message: string;
            request_id: string;
        };
        /**
         * @description ISO-8601(`2026-09-01T00:00:00+09:00`) 또는 상대식. 상대식 문법: `now`, `now-<n><unit>` (unit ∈ s,m,h,d,w,M), 경계 정렬 `/d`, `/w`, `/M`
         *     (예 `now-7d/d` = 7일 전 자정). Grafana 상대 시간식 차용, 단 **서버가 해석**하고 응답에 `resolved_from/to`를 돌려준다.
         * @example now-7d
         * @example now/d
         * @example 2026-08-31T00:00:00+09:00
         */
        TimeExpr: string;
        /**
         * @description 버킷 크기. 생략 시 서버가 `max(min_interval, range / max_data_points)` 로 결정 (Grafana step 규칙). 응답 `meta.resolved_interval`.
         * @enum {string}
         */
        Interval: "1h" | "6h" | "1d" | "1w" | "1M";
        /**
         * @description list=공시 단가(cost_usd 보고값/추정값) · contract=계약 단가(× contract_token_discounts.discount_rate, 가정 A5)
         * @enum {string}
         */
        PriceBasis: "list" | "contract";
        /** @enum {string} */
        PageId: "P1" | "P2" | "P3" | "P4" | "P5";
        /**
         * @description available=현 스키마로 산출 · partial=일부 차원 대리 측정 · unavailable=어댑터 드롭/원문/외부 데이터 의존(부록)
         * @enum {string}
         */
        Availability: "available" | "partial" | "unavailable";
        /**
         * @description enrollment.members.role
         * @enum {string}
         */
        MemberRole: "owner" | "admin" | "member";
        /**
         * @description enrollment.members.status
         * @enum {string}
         */
        MemberStatus: "invited" | "active" | "suspended";
        /** @description 전역 필터 바와 1:1. 빈 배열은 "전체". */
        GlobalFilters: {
            /** @description enrollment.teams.id → ClickHouse `hasAny(team_ids_as_of, team_ids)` */
            team_ids?: string[];
            /** @description enriched_events.product */
            products?: ("claude_code" | "codex")[];
            /** @description raw_json.payload.model (log/span) 또는 raw_json.point.attrs.model (metric) */
            models?: string[];
            /** @description P3 전용. members.id → installations.id 목록으로 해석해 `installation_id IN (...)` (가정 A3). X-Audit-Reason 필수 */
            member_ids?: string[];
        };
        QueryRequest: {
            from: components["schemas"]["TimeExpr"];
            to: components["schemas"]["TimeExpr"];
            /** @description 버킷 경계 타임존. 기본 tenants.timezone */
            tz?: string;
            /**
             * @description 비교 시리즈 추가 (`*_compare` 필드). previous_period=같은 길이의 직전 구간, previous_week=7일 전 같은 구간
             * @default none
             * @enum {string}
             */
            compare?: "none" | "previous_period" | "previous_week";
            filters?: components["schemas"]["GlobalFilters"];
            price_basis?: components["schemas"]["PriceBasis"];
            /**
             * @description 위젯 폭에서 나온 상한. `interval` 미지정 시 step 결정에 쓰임
             * @default 500
             */
            max_data_points?: number;
            queries: components["schemas"]["Query"][];
        };
        Query: {
            /** @description 응답 results 의 키 */
            ref_id: string;
            metric_id: components["schemas"]["MetricId"];
            /** @description 허용 조합은 META-METRICS 의 `allowed_group_by`. 프레임은 group 조합마다 하나(라벨은 fields[].labels) */
            group_by?: components["schemas"]["Dimension"][];
            interval?: components["schemas"]["Interval"];
            /**
             * @description 생략 시 지표 기본형(META-METRICS.default_frame_type). distribution=버킷·분위수, scalar=KPI 단일값(+비교값)
             * @enum {string}
             */
            frame_type?: "timeseries" | "table" | "distribution" | "scalar";
            /**
             * @description `cost`·`tokens` 전용. events=raw_json.payload(llm_call, 두 제품 공통) · metrics=raw_json.point(claude_code 메트릭, agent_name/skill_name 등 귀속 차원 가능)
             * @enum {string}
             */
            source?: "events" | "metrics";
            /** @description table/group 상위 N (나머지는 `__other__`) */
            limit?: number;
            /**
             * @default value_desc
             * @enum {string}
             */
            order?: "value_desc" | "value_asc" | "label_asc";
            /** @description 이 쿼리만 덮어쓰는 필터 */
            filters?: components["schemas"]["GlobalFilters"];
            price_basis?: components["schemas"]["PriceBasis"];
            /** @description 지표별 추가 파라미터 (META-METRICS.params_schema). 예 cost_anomaly.moving_avg_days, rubber_stamp_ratio.threshold_ms */
            params?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description 지표 카탈로그 키. 정의·컬럼 매핑·참조 SQL은 overview §4. `(A-1)` 등은 지표보고서 ID.
         * @enum {string}
         */
        MetricId: "telemetry_coverage" | "active_users" | "adoption_rate" | "sessions" | "active_time" | "automation_ratio" | "prompts_per_session" | "command_prompt_ratio" | "lines_of_code" | "commits" | "pull_requests" | "integration_depth" | "cost" | "cost_anomaly" | "cost_per_active_user" | "cost_per_user_hour" | "tokens" | "cache_read_ratio" | "input_output_ratio" | "subagent_cost_ratio" | "model_users" | "model_unit_price" | "contract_commitment_burn" | "compactions" | "compaction_reduction" | "edit_acceptance_rate" | "auto_approval_ratio" | "gate_wait_ms" | "tool_rejections" | "rubber_stamp_ratio" | "mcp_connections" | "mcp_failure_ratio" | "subagent_activity" | "api_error_rate" | "api_retry_attempts" | "rate_limit_events" | "tool_calls" | "tool_failure_rate" | "read_tool_density" | "turn_duration_ms" | "llm_ttft_ms" | "llm_duration_ms" | "llm_stop_reasons" | "hook_executions" | "hook_blocking" | "refusals" | "vendor_account_mismatch" | "usage_heatmap" | "usage_concentration" | "onboarding_ttfu" | "onboarding_retention" | "abandoned_session_ratio" | "session_last_event";
        /**
         * @description group_by 차원. 괄호는 원천 컬럼.
         * @enum {string}
         */
        Dimension: "team" | "product" | "model" | "start_type" | "type" | "query_source" | "agent_name" | "skill_name" | "plugin_name" | "mcp_server" | "speed" | "effort" | "language" | "decided_by" | "decision" | "tool_name" | "tool_kind" | "action" | "error_type" | "status_code" | "stop_reason" | "server_name" | "server_scope" | "transport_type" | "is_plugin" | "trigger" | "category" | "hook_event" | "client_version" | "platform" | "hour" | "weekday";
        QueryResponse: {
            request_id: string;
            /** Format: date-time */
            resolved_from: string;
            /** Format: date-time */
            resolved_to: string;
            /** Format: date-time */
            compare_from?: string | null;
            /** Format: date-time */
            compare_to?: string | null;
            /** @description 모든 응답에 동봉 — 화면 고정 캡션용 (H-1) */
            coverage?: {
                /** @description uniqExact(installation_id) 기간 내 이벤트 있음 */
                active_installations?: number;
                /** @description count(members) status='active' */
                active_members?: number;
                ratio?: number | null;
                /**
                 * Format: date-time
                 * @description max(ts)
                 */
                last_ingested_at?: string;
            };
            results: {
                [key: string]: components["schemas"]["QueryResult"];
            };
        };
        QueryResult: {
            /** @description 200 또는 쿼리 단위 오류 코드 */
            status: number;
            error?: components["schemas"]["Error"];
            frames: components["schemas"]["Frame"][];
        };
        /** @description 열 지향 DataFrame (Grafana 차용). group 조합마다 프레임 하나, 라벨은 필드에. */
        Frame: {
            schema: {
                ref_id: string;
                metric_id: components["schemas"]["MetricId"];
                /** @enum {string} */
                frame_type: "timeseries" | "table" | "distribution" | "scalar";
                fields: components["schemas"]["Field"][];
                meta?: {
                    resolved_interval?: components["schemas"]["Interval"];
                    /** @description 계산식 한 줄 (툴팁 ⓘ) */
                    definition?: string;
                    /** @description 함정·오독 경고 (예 청구액 아님) */
                    caveat?: string;
                    /**
                     * @description active_users 계열 — 어느 정의가 적용됐는지 (가정 A2)
                     * @enum {string}
                     */
                    active_user_definition?: "active_time_user" | "any_event";
                    /** @description 응답 필드 ↔ ClickHouse/RDB 컬럼 (raw_json.<path> 표기) */
                    source_columns?: string[];
                    /** @description 실제 실행 SQL (owner/admin 에게만) */
                    executed_sql?: string;
                    /** @description n<5 로 마스킹된 group 라벨 */
                    suppressed_groups?: string[];
                    /** @description 예 "cumulative temporality 포인트 12개 제외(가정 A1)", "installation_id 없는 이벤트 3% 제외" */
                    data_quality?: string[];
                };
            };
            data: {
                /** @description fields 와 같은 길이의 평행 배열. time 필드는 epoch ms */
                values: unknown[][];
            };
        };
        Field: {
            name: string;
            /** @enum {string} */
            type: "time" | "number" | "string" | "boolean";
            /** @description group_by 키 값 (예 team_id, team_name, model). 행이 아니라 필드에 붙는다 */
            labels?: {
                [key: string]: string;
            };
            config?: {
                /**
                 * @example USD
                 * @example token
                 * @example ms
                 * @example s
                 * @example count
                 * @example ratio
                 * @example percent
                 * @example lines
                 */
                unit?: string;
                display_name?: string;
                interval_ms?: number;
                /** @description n<5 마스킹 — 값은 null */
                suppressed?: boolean;
                /** @description 비율 지표의 분모 (0이면 값 null) */
                denominator?: number | null;
                numerator?: number | null;
                /** @description 이 group 의 활성 사용자 수 (마스킹 근거) */
                group_size?: number;
                /** @description distribution 프레임의 분위수 목록 */
                percentiles?: number[];
            };
        };
        MetricDefinition: {
            metric_id?: components["schemas"]["MetricId"];
            /** @description 지표보고서/시나리오 ID (A-1 */
            indicator_id?: string;
            title?: string;
            definition?: string;
            caveat?: string;
            unit?: string;
            availability?: components["schemas"]["Availability"];
            /** @enum {string} */
            default_frame_type?: "timeseries" | "table" | "distribution" | "scalar";
            allowed_group_by?: components["schemas"]["Dimension"][];
            /** @description 예 refusals → [team] */
            forbidden_group_by?: components["schemas"]["Dimension"][];
            /** @default 5 */
            min_group_size?: number;
            source_columns?: string[];
            /** @description JSON Schema */
            params_schema?: {
                [key: string]: unknown;
            };
            /** @description overview §4 의 참조 SQL 번호 */
            sql_template_id?: string;
        };
        TeamOption: {
            /**
             * Format: uuid
             * @description teams.id
             */
            team_id?: string;
            /** @description teams.name */
            name?: string;
            /**
             * @description teams.status
             * @enum {string}
             */
            status?: "active" | "archived";
            /** @description count(team_memberships) where left_at IS NULL and members.status='active' */
            member_count?: number;
        };
        ModelOption: {
            /** @description DISTINCT raw_json.payload.model ∪ raw_json.point.attrs.model */
            model?: string;
            product?: string;
            /**
             * @description Pricing 표 접두 매칭으로 추정
             * @enum {string}
             */
            vendor?: "anthropic" | "openai" | "google" | "unknown";
        };
        /** @description raw_json 을 그대로 펼친 이벤트 한 건 (원문 필드는 애초에 없음 — ADR 0017 규칙 1) */
        SessionEvent: {
            /** @description enriched_events.event_id */
            event_id?: string;
            /**
             * Format: date-time
             * @description enriched_events.ts
             */
            ts?: string;
            /**
             * @description enriched_events.signal
             * @enum {string}
             */
            signal?: "log" | "span" | "metric";
            /** @description raw_json.type (로그·스팬) 또는 raw_json.point.name (메트릭) */
            type?: string;
            /** @description raw_json.turn_id */
            turn_id?: string | null;
            /** @description raw_json.call_id */
            call_id?: string | null;
            /** @description raw_json.envelope._ingest.call_id_inferred */
            call_id_inferred?: boolean;
            /** @description raw_json.span_id */
            span_id?: string | null;
            /** @description raw_json.parent_id */
            parent_id?: string | null;
            /** @description raw_json.sequence */
            sequence?: number | null;
            /** @description raw_json.payload 또는 raw_json.point (그대로) */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description 시나리오 문서 8 카테고리 — 1 비용·토큰·예산 / 2 사용 패턴·시간대·Rate Limit / 3 도입·채택 / 4 생산성·활용 역량 / 5 보안·컴플라이언스 / 6 품질·신뢰성·성능·운영 / 7 거버넌스·에이전트·리스크 / 8 ROI·전략·경영 보고
         * @enum {string}
         */
        ScenarioCategory: "cost" | "usage_pattern" | "adoption" | "productivity" | "security" | "quality" | "governance" | "strategy";
        ScenarioSummary: {
            /** @example S1-3 */
            scenario_id: string;
            category: components["schemas"]["ScenarioCategory"];
            title: string;
            /** @description 한 줄 상황 */
            situation?: string;
            /** @description 시나리오 문서 ⭐ */
            featured?: boolean;
            availability: components["schemas"]["Availability"];
            unavailable_reason?: string | null;
            target_page: components["schemas"]["PageId"];
            /** @description 결과 뷰에서 강조할 위젯 ID (디자인 프롬프트 W*.*) */
            highlight_widgets?: string[];
            required_params?: string[];
            metric_ids?: components["schemas"]["MetricId"][];
        };
        ScenarioDetail: components["schemas"]["ScenarioSummary"] & {
            metrics?: {
                metric_id?: components["schemas"]["MetricId"];
                indicator_id?: string;
                availability?: components["schemas"]["Availability"];
                definition?: string;
                caveat?: string;
            }[];
            /** @description JSON Schema — 파라미터 폼 생성용 */
            params_schema?: {
                [key: string]: unknown;
            };
            findings_rules?: {
                rule_id?: string;
                /** @enum {string} */
                severity?: "info" | "warning" | "anomaly";
                /** @description 판정식 (서버 평가) */
                when?: string;
                /** @description 템플릿 */
                message?: string;
            }[];
            /** @description 시나리오 문서 "인사이트 → 액션" */
            actions?: string[];
        };
        /** @enum {string} */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        ScenarioRunSummary: {
            /**
             * Format: uuid
             * @description dashboard.scenario_runs.id
             */
            run_id?: string;
            scenario_id?: string;
            status?: components["schemas"]["RunStatus"];
            /** @description 예 "28d · 팀 3 · 임계 +200%" */
            params_summary?: string;
            created_by?: {
                member_id?: string;
                display_name?: string;
            };
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            finished_at?: string | null;
            findings_count?: {
                anomaly?: number;
                warning?: number;
                info?: number;
            };
            /** Format: uuid */
            saved_id?: string | null;
        };
        ScenarioRun: components["schemas"]["ScenarioRunSummary"] & {
            params?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            resolved_from?: string;
            /** Format: date-time */
            resolved_to?: string;
            progress?: {
                step?: number;
                total?: number;
                /** @description 예 "쿼리 실행 2/3" */
                label?: string;
            };
            error?: components["schemas"]["Error"];
            /** @description status=succeeded 일 때 */
            result?: {
                target_page?: components["schemas"]["PageId"];
                /** @description 결과 뷰가 전역 필터 바에 적용할 값 (QueryRequest 상위 필드와 같은 모양) */
                applied_filters?: {
                    [key: string]: unknown;
                };
                highlight_widgets?: string[];
                findings?: components["schemas"]["Finding"][];
                /** @description metric_id → QueryResult (결과 뷰 위젯이 재조회 없이 그릴 수 있게 동봉) */
                frames?: {
                    [key: string]: components["schemas"]["QueryResult"];
                };
            } | null;
        };
        Finding: {
            rule_id: string;
            /** @enum {string} */
            severity: "info" | "warning" | "anomaly";
            title: string;
            /** @description 근거 지표·값 */
            evidence?: {
                [key: string]: unknown;
            };
            /** @description '관련 위젯으로 이동' 링크 대상 */
            widget_id?: string | null;
            action?: string | null;
        };
        SavedReport: {
            /**
             * Format: uuid
             * @description dashboard.saved_reports.id
             */
            saved_id?: string;
            /** Format: uuid */
            run_id?: string;
            scenario_id?: string;
            name?: string;
            note?: string | null;
            /** @enum {string} */
            time_mode?: "fixed" | "relative";
            created_by?: {
                member_id?: string;
                display_name?: string;
            };
            /** Format: date-time */
            created_at?: string;
            /** @description 예 /runs/9b3d… (같은 테넌트 관리자만) */
            share_path?: string;
        };
        Page: {
            next_cursor?: string | null;
            /** @description 계산 비용이 크면 null */
            total?: number | null;
        };
    };
    responses: {
        /** @description 잘못된 요청 (파라미터·group_by 조합·시간식) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 토큰 없음 또는 무효 (둘을 구분하지 않음 — enrollment 서버 관례) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "unauthorized",
                 *       "message": "Invalid or expired credential",
                 *       "request_id": "a1b2…"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 역할·팀 범위 밖, 또는 감사 사유 없음 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 없음 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "not_found",
                 *       "message": "Not found",
                 *       "request_id": "a1b2…"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 기간×해상도가 상한 초과 (max_data_points 또는 90일×1h 등) */
        QueryTooWide: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "query_too_wide",
                 *       "message": "interval=1h 로 90일은 점 2160개로 상한(1000)을 넘습니다. interval 을 키우거나 기간을 줄이세요.",
                 *       "request_id": "a1b2…"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description ClickHouse 쿼리 시간 초과 (기본 30초) */
        QueryTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "query_timeout",
                 *       "message": "쿼리 시간 초과 — 기간을 줄이거나 팀을 좁혀 다시 실행하세요.",
                 *       "request_id": "a1b2…"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description 클라이언트 취소·추적용. **서버 의미 없음** (Grafana requestId 와 같은 성격). 응답 `request_id`는 서버가 새로 발급한다. */
        XRequestId: string;
        /** @description 개인 식별 조회(member_ids 필터, 이메일 전체 표시)에 필요. 감사 로그에 기록. */
        XAuditReason: string;
        /** @description 조회 사유. 감사 로그(조회자·시각·대상·사유)에 기록. */
        XAuditReasonRequired: string;
        From: components["schemas"]["TimeExpr"];
        To: components["schemas"]["TimeExpr"];
        Limit: number;
        /** @description 이전 응답의 `next_cursor` (불투명 문자열) */
        Cursor: string;
        ScenarioId: string;
        RunId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "AUTH-LOGIN": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token?: string;
                        /** @constant */
                        token_type?: "Bearer";
                        /** @description 초 */
                        expires_in?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    ME: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description enrollment.members.id
                         */
                        member_id?: string;
                        /** @description enrollment.members.email */
                        email?: string;
                        /** @description enrollment.members.display_name */
                        display_name?: string;
                        role?: components["schemas"]["MemberRole"];
                        tenant?: {
                            /**
                             * Format: uuid
                             * @description enrollment.tenants.id
                             */
                            id?: string;
                            /** @description enrollment.tenants.name */
                            name?: string;
                            /** @description enrollment.tenants.timezone (기본 Asia/Seoul) */
                            timezone?: string;
                        };
                        /** @description role=admin 이면 team_memberships(left_at IS NULL) 기준 자기 팀, owner 면 전체 */
                        accessible_team_ids?: string[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    QRY: {
        parameters: {
            query?: never;
            header?: {
                /** @description 클라이언트 취소·추적용. **서버 의미 없음** (Grafana requestId 와 같은 성격). 응답 `request_id`는 서버가 새로 발급한다. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
                /** @description 개인 식별 조회(member_ids 필터, 이메일 전체 표시)에 필요. 감사 로그에 기록. */
                "X-Audit-Reason"?: components["parameters"]["XAuditReason"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description 쿼리별 결과. 개별 쿼리 실패는 해당 `results[ref_id].status`와 `error`로 표시(전체 200). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                    "text/csv": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["QueryTooWide"];
            504: components["responses"]["QueryTimeout"];
        };
    };
    "META-METRICS": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["MetricDefinition"][];
                    };
                };
            };
        };
    };
    "META-FILTERS": {
        parameters: {
            query?: {
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        teams?: components["schemas"]["TeamOption"][];
                        /** @description SELECT DISTINCT product FROM enriched_events (기간 내) */
                        products?: ("claude_code" | "codex")[];
                        models?: components["schemas"]["ModelOption"][];
                        time_presets?: string[];
                        price_bases?: components["schemas"]["PriceBasis"][];
                    };
                };
            };
        };
    };
    "META-TEAMS": {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["TeamOption"][];
                    };
                };
            };
        };
    };
    "META-MEMBERS": {
        parameters: {
            query?: {
                team_id?: string;
                status?: components["schemas"]["MemberStatus"];
                limit?: components["parameters"]["Limit"];
                /** @description 이전 응답의 `next_cursor` (불투명 문자열) */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: {
                /** @description 개인 식별 조회(member_ids 필터, 이메일 전체 표시)에 필요. 감사 로그에 기록. */
                "X-Audit-Reason"?: components["parameters"]["XAuditReason"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: {
                            /**
                             * Format: uuid
                             * @description members.id
                             */
                            member_id?: string;
                            /** @description members.email */
                            email?: string;
                            /** @description members.display_name */
                            display_name?: string | null;
                            role?: components["schemas"]["MemberRole"];
                            status?: components["schemas"]["MemberStatus"];
                            /** @description team_memberships where left_at IS NULL */
                            team_ids?: string[];
                            /** @description count(installations) where status='active' */
                            installation_count?: number;
                            /**
                             * Format: date-time
                             * @description max(installations.last_seen_at)
                             */
                            last_seen_at?: string | null;
                        }[];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    "META-MODELS": {
        parameters: {
            query?: {
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["ModelOption"][];
                    };
                };
            };
        };
    };
    "META-CONTRACTS": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: {
                            /**
                             * Format: uuid
                             * @description contracts.id
                             */
                            contract_id?: string;
                            /**
                             * @description contracts.vendor
                             * @enum {string}
                             */
                            vendor?: "anthropic" | "openai" | "google";
                            /**
                             * @description contracts.contract_type
                             * @enum {string}
                             */
                            contract_type?: "term_commitment" | "token_discount";
                            /** @description contracts.name */
                            name?: string;
                            /** @description contracts.contract_no */
                            contract_no?: string | null;
                            /**
                             * Format: date
                             * @description contracts.starts_at
                             */
                            starts_at?: string;
                            /**
                             * Format: date
                             * @description contracts.ends_at
                             */
                            ends_at?: string | null;
                            /**
                             * @description contracts.status
                             * @enum {string}
                             */
                            status?: "draft" | "active" | "expired" | "terminated";
                            /** @description count(contract_memberships) where released_at IS NULL */
                            member_count?: number;
                            term_commitment?: {
                                /** @description contract_term_commitments.commitment_months */
                                commitment_months?: number;
                                /** @description contract_term_commitments.commitment_amount */
                                commitment_amount?: number | null;
                                /** @description contract_term_commitments.currency */
                                currency?: string;
                                /** @description contract_term_commitments.auto_renew */
                                auto_renew?: boolean;
                            } | null;
                            token_discounts?: {
                                /** @description contract_token_discounts.model_pattern (부분 문자열 매칭, 가정 A5) */
                                model_pattern?: string | null;
                                /**
                                 * @description contract_token_discounts.token_type
                                 * @enum {string}
                                 */
                                token_type?: "input" | "output" | "cache_read" | "cache_create" | "all";
                                /** @description contract_token_discounts.discount_rate — 정가에 곱하는 배율 */
                                discount_rate?: number;
                                /**
                                 * Format: date
                                 * @description contract_token_discounts.effective_from
                                 */
                                effective_from?: string;
                                /**
                                 * Format: date
                                 * @description contract_token_discounts.effective_to
                                 */
                                effective_to?: string | null;
                            }[];
                        }[];
                    };
                };
            };
        };
    };
    "META-MANIFESTS": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        active?: {
                            /**
                             * Format: uuid
                             * @description manifests.id
                             */
                            manifest_id?: string;
                            /** @description manifests.version */
                            version?: number;
                            /**
                             * Format: date-time
                             * @description manifests.activated_at
                             */
                            activated_at?: string | null;
                            /** @description manifests.manifest(jsonb).signals — logs/metrics/traces 활성 여부 */
                            signals?: {
                                [key: string]: boolean;
                            };
                            /** @description count(installation_manifest_assignments) where applied_at IS NOT NULL */
                            applied_installations?: number;
                            /** @description count(installation_manifest_assignments) */
                            assigned_installations?: number;
                        } | null;
                        history?: {
                            version?: number;
                            /** Format: date-time */
                            created_at?: string;
                            is_active?: boolean;
                        }[];
                    };
                };
            };
        };
    };
    "INSTALL-LIST": {
        parameters: {
            query?: {
                /** @description 이 일수 이상 이벤트가 없는 설치만 (30/60/90) */
                inactive_days?: number;
                team_id?: string;
                platform?: "windows" | "macos" | "linux";
                status?: "active" | "revoked";
                limit?: components["parameters"]["Limit"];
                /** @description 이전 응답의 `next_cursor` (불투명 문자열) */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: {
                /** @description 개인 식별 조회(member_ids 필터, 이메일 전체 표시)에 필요. 감사 로그에 기록. */
                "X-Audit-Reason"?: components["parameters"]["XAuditReason"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: {
                            /**
                             * Format: uuid
                             * @description installations.id
                             */
                            installation_id?: string;
                            /** @description members.email (X-Audit-Reason 없으면 도메인만) */
                            member_email_masked?: string;
                            team_ids?: string[];
                            /** @description installations.hostname */
                            hostname?: string | null;
                            /** @description installations.platform */
                            platform?: string;
                            /** @description installations.client_version */
                            client_version?: string | null;
                            /** @description installations.status */
                            status?: string;
                            /**
                             * Format: date-time
                             * @description installations.created_at
                             */
                            created_at?: string;
                            /**
                             * Format: date-time
                             * @description installations.last_seen_at
                             */
                            last_seen_at?: string | null;
                            /**
                             * Format: date-time
                             * @description max(enriched_events.ts) where installation_id
                             */
                            last_event_at?: string | null;
                            /** @description argMax(raw_json.envelope.client.version, ts) by product */
                            product_versions?: {
                                [key: string]: string;
                            };
                        }[];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    "SESSION-EVENTS": {
        parameters: {
            query?: {
                /** @description session_id 대신 다른 키로 세션을 찾을 때 */
                lookup?: "session_id" | "request_id" | "call_id" | "installation_id";
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
                limit?: components["parameters"]["Limit"];
                /** @description 이전 응답의 `next_cursor` (불투명 문자열) */
                cursor?: components["parameters"]["Cursor"];
            };
            header: {
                /** @description 조회 사유. 감사 로그(조회자·시각·대상·사유)에 기록. */
                "X-Audit-Reason": components["parameters"]["XAuditReasonRequired"];
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        session?: {
                            /** @description raw_json.envelope.session_id */
                            session_id?: string;
                            /** @description enriched_events.product */
                            product?: string;
                            /** @description raw_json.envelope.client.version */
                            client_version?: string | null;
                            /** @description enriched_events.installation_id */
                            installation_id?: string;
                            /** @description enriched_events.team_ids_as_of (첫 이벤트 기준) */
                            team_ids?: string[];
                            /**
                             * Format: date-time
                             * @description min(ts)
                             */
                            started_at?: string;
                            /**
                             * Format: date-time
                             * @description max(ts)
                             */
                            ended_at?: string;
                            event_count?: number;
                        };
                        items?: components["schemas"]["SessionEvent"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    "SCN-LIST": {
        parameters: {
            query?: {
                category?: components["schemas"]["ScenarioCategory"];
                availability?: components["schemas"]["Availability"];
                target_page?: components["schemas"]["PageId"];
                /** @description 제목·상황 텍스트 검색 */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        categories?: {
                            id?: components["schemas"]["ScenarioCategory"];
                            title?: string;
                            /** @description 카테고리 핵심 질문 */
                            question?: string;
                            persona?: string;
                        }[];
                        items?: components["schemas"]["ScenarioSummary"][];
                    };
                };
            };
        };
    };
    "SCN-GET": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: components["parameters"]["ScenarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    "SCN-RUN": {
        parameters: {
            query?: {
                wait?: boolean;
            };
            header?: {
                /** @description 클라이언트 취소·추적용. **서버 의미 없음** (Grafana requestId 와 같은 성격). 응답 `request_id`는 서버가 새로 발급한다. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path: {
                scenario_id: components["parameters"]["ScenarioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description SCN-GET의 params_schema를 따르는 값. 기간은 상대식 허용. */
                    params: {
                        [key: string]: unknown;
                    };
                    price_basis?: components["schemas"]["PriceBasis"];
                    /** @description 기본 테넌트 timezone */
                    tz?: string;
                };
            };
        };
        responses: {
            /** @description wait=true 이고 20초 안에 완료됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRun"];
                };
            };
            /** @description 큐에 들어감 */
            202: {
                headers: {
                    /** @description /v1/scenario-runs/{run_id} */
                    Location?: string;
                    /** @description 권장 폴링 간격(초) */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description availability=unavailable 인 시나리오 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "scenario_unavailable",
                     *       "message": "이 시나리오는 어댑터 확장(skill_activated 이벤트 보존) 후 실행할 수 있습니다.",
                     *       "request_id": "1c2d…"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 테넌트당 동시 실행 상한(기본 3) 초과 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "RUN-LIST": {
        parameters: {
            query?: {
                scenario_id?: string;
                status?: components["schemas"]["RunStatus"];
                created_by?: string;
                limit?: components["parameters"]["Limit"];
                /** @description 이전 응답의 `next_cursor` (불투명 문자열) */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["ScenarioRunSummary"][];
                    };
                };
            };
        };
    };
    "RUN-GET": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    /** @description status ∈ {queued, running} 일 때만 */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRun"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    "RUN-DELETE": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    "RUN-CANCEL": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRun"];
                };
            };
            /** @description 이미 종료된 실행 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "RUN-SAVE": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    note?: string;
                    /**
                     * @description fixed=실행 시점의 절대 기간 고정 / relative=열 때마다 상대식 재실행
                     * @default fixed
                     * @enum {string}
                     */
                    time_mode?: "fixed" | "relative";
                };
            };
        };
        responses: {
            /** @description 생성됨 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedReport"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    "SAVED-LIST": {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description 이전 응답의 `next_cursor` (불투명 문자열) */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        items?: components["schemas"]["SavedReport"][];
                    };
                };
            };
        };
    };
    "SAVED-DELETE": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                saved_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
}
